### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by DarrynJ** [DarrynJ/task-api-assessment#16]
Add the following tests: 

### Users
- [ ] Login User
- [ ] Create User
- [ ] Get User
- [ ] Update User
- [ ] Delete User

### Tasks
- [ ] Create Task
- [ ] Get Task
- [ ] Get All Tasks
- [ ] Get Assignee Tasks
- [ ] Get Expired Tasks
- [ ] Get Active Tasks
- [ ] Get Tasks From Date
- [ ] Update Task
- [ ] Delete Task
